[package]
name = "meetingtime"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio              = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync", "tracing"] }
console-subscriber = "0.5"
clap        = { version = "4", features = ["derive"] }
reqwest     = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
chrono      = { version = "0.4", features = ["serde"] }
oauth2      = { version = "4", features = ["reqwest"] }
notify-rust = "4"
open        = "5"
dirs        = "5"
anyhow      = "1"

[target.'cfg(target_os = "macos")'.dependencies]
mac-notification-sys = "0.6"
